# Generated by Django 4.1.2 on 2023-01-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('descriptions', models.CharField(max_length=1000)),
                ('key_skills', models.CharField(max_length=1000)),
                ('department', models.CharField(max_length=1000)),
                ('salary_from', models.CharField(max_length=1000)),
                ('salary_to', models.CharField(max_length=1000)),
                ('area_name', models.CharField(max_length=1000)),
                ('published_at', models.CharField(max_length=1000)),
            ],
        ),
    ]
