# Generated by Django 4.1.2 on 2023-01-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_vacancyrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountVacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('countVacancies', models.CharField(max_length=10)),
                ('vacanciesDevops', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LevelSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('averageSalary', models.CharField(max_length=10)),
                ('salaryDevops', models.CharField(max_length=10)),
            ],
        ),
    ]
